DROP TABLE IF EXISTS `Directions`;
CREATE TABLE `Directions` (`ID` integer PRIMARY KEY, `Name` char(128) NOT NULL, `X` float(128), `Y` float(128), `Z` float(128), `InvertID` integer, `Colour` char(8));
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (1,'North',0,-1.25,0,5, '#FF6813');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (2,'NorthEast',1,-1,0,6, '#3DA421');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (3,'East',1,0,0,7, '#3DA4D4');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (4,'SouthEast',1,1,0,8, '#764BFF');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (5,'South',0,1.25,0,1, '#FF6813');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (6,'SouthWest',-1,1,0,2, '#3DA421');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (7,'West',-1,0,0,3, '#3DA4D4');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (8,'NorthWest',-1,-1,0,4, '#764BFF');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (9,'Up',-0.5,-1,1,10, '#B91D00');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (10,'Down',0.5,1,-1,9, '#B91D00');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (11,'Enter',0.5,0.5,0.5,12, '#32A4A7');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (12,'Exit',-0.5,-0.5,-0.5,11, '#32A4A7');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (13,'Port',-1,0,0,14, '#3DA4D4');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (14,'Starboard',1,0,0,13, '#3DA4D4');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (15,'Afore',0,-1,0,16, '#FF6813');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (16,'Astern',0,1,0,15, '#FF6813');
INSERT INTO `Directions` (`ID`,`Name`,`X`,`Y`,`Z`,`InvertID`, `Colour`) VALUES (17,'Special/Magic',-1,0.5,0,17, '#FF2FA9');
DROP TABLE IF EXISTS `Paths`;
CREATE TABLE `Paths` (`DirectionID` integer, `FromID` integer, `ToID` integer);
INSERT INTO `Paths` (`DirectionID`,`FromID`,`ToID`) VALUES (1,2,1);
INSERT INTO `Paths` (`DirectionID`,`FromID`,`ToID`) VALUES (5,1,2);
DROP TABLE IF EXISTS `Rooms`;
CREATE TABLE `Rooms` (`ID` integer PRIMARY KEY AUTOINCREMENT, `Name` char(255) NOT NULL, `Description` varchar(255));
INSERT INTO `Rooms` (`ID`,`Name`,`Description`) VALUES (1,'First Room','A place to start');
INSERT INTO `Rooms` (`ID`,`Name`,`Description`) VALUES (2,'Second room','Somewhere to go');
DROP TABLE IF EXISTS `Objects`;
CREATE TABLE IF NOT EXISTS `Objects` (`ID` integer PRIMARY KEY, `Name` char(128),`FoundRoom` integer,`CurrentRoom` integer,
  `Aliases` char(128));